version: "3.8"

services:
  ita-db:
    image: postgres:13.4-alpine
    container_name: itadb-dev-data
    volumes:
      - itadb-dev-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ita-net
    ports:
      - "10090:5432"

  ita-redis:
    image: redis:6.2.5-alpine
    container_name: redis-dev-data
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    networks:
      - ita-net

  ita-api:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: ita-api:dev
    container_name: ita-api-dev
    platform: linux/x86_64
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 10091:$PORT
    networks:
      - ita-net
    depends_on:
      - ita-db
      - ita-redis

volumes:
  itadb-dev-data:
    name: itadb-dev-data

networks:
  ita-net:
    name: ita-net
    driver: bridge
