# stage one
FROM node:14 as builder

# install dependencies for node-gyp
# RUN apk add --no-cache python make g++

WORKDIR /app

COPY ./package.json prisma ./
RUN npm install

# stage two
FROM node:14

ENV NODE_ENV=development

# USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY . .
COPY --from=builder /app/node_modules /home/node/app/node_modules

CMD [ "npm", "run", "start:dev" ]