@startuml

skinparam linetype ortho

enum Status {
  PAID
  PENDING
  CANCELLED
}

entity UserRole {
  * id: Int
  * name: String
  * admin: Boolean
  * developer: Boolean
  * manager: Boolean
  * registered: Boolean
  * user: User[]
}

entity UserStatus {
  * id: Int
  * name: String
  * active: Boolean
  * pending: Boolean
  * suspended: Boolean
  * deleted: Boolean
  * user: User[]
}

entity User {
  * id: Int
  name: String?
  lastnames: String?
  * email: String
  * password: String
  * createdAt: DateTime
  * updatedAt: DateTime
  * userStatus: UserStatus
  * userStatusId: Int
  * userRole: UserRole
  * userRoleId: Int
  * accesLog: AccesLog[]
  * recoverPassword: RecoverPasswordLog[]
  * media: Media[]
  * ads: Ads[]
  avatar: Media?
  avatarId: Int?
  developerData: Json?
  * messagesSent: Message[]
  * userConversations: UserConversation[]
  * userInvoices: Invoice[]
}

entity AccesLog {
  * id: Int
  * login: DateTime
  * logout: DateTime
  * user: User
  * userId: Int
}

entity RecoverPasswordLog {
  * id: Int
  * createdAt: DateTime
  * password: String
  * user: User
  * userId: Int
}

entity Media {
  * id: Int
  * path: String
  * mimeType: String
  * fileSize: String
  * user: User
  * userId: Int
  avatar: User?
  * mediaMeta: MediaMeta[]
}

entity MediaMeta {
  * id: Int
  * path: String
  * mimeType: String
  * fileSize: String
  * media: Media
  * mediaId: Int
  * mediaType: MediaType
  * mediaTypeId: Int
}

entity MediaType {
  * id: Int
  * name: String
  * thumnail: Boolean
  * medium: Boolean
  * large: Boolean
  * original: Boolean
  * mediaMeta: MediaMeta[]
}

entity LevelType {
  * id: Int
  * name: String
  * country: Int
  * state: Int
  * city: Int
  * town: Int
  * district: Int
  * neighborhood: Int
  * level: Level[]
}

entity Level {
  * id: Int
  * name: String
  parent: Level?
  parentId: Int?
  * child: Level[]
  * levelType: LevelType
  * levelTypeId: Int
}

entity AdType {
  * id: Int
  * name: String
  * house: Int
  * room: Int
  * garage: Int
  * storage: Int
  * office: Int
  * warehouse: Int
  * building: Int
  * newBuilding: Int
  * ads: Ads[]
}

entity AdStatus {
  * id: Int
  * name: String
  * unPublish: Int
  * publish: Int
  * ads: Ads[]
}

entity Ads {
  * id: Int
  * user: User
  * userId: Int
  * title: String
  * description: String
  * nRooms: Int
  * price: Int
  * includedExpenses: Boolean
  * squareMeters: Int
  * nBathrooms: Int
  * city: String
  * mapLat: Decimal
  * mapLon: Decimal
  * adType: AdType
  * adTypeId: Int
  * adStatus: AdStatus
  * adStatusId: Int
  * createdAt: DateTime
  * updatedAt: DateTime
}

entity Conversation {
  * id: Int
  * messages: Message[]
  * participants: UserConversation[]
}

entity UserConversation {
  * id: Int
  * user: User
  * userId: Int
  * conversation: Conversation
  * conversationId: Int
}

entity Message {
  * id: Int
  * sender: User
  * senderId: Int
  * conversation: Conversation
  * conversationId: Int
  * text: String
  * createdAt: DateTime
}

entity Invoice {
  * id: Int
  * user: User
  * userId: Int
  billingaddress: String?
  postalCode: String?
  * city: String
  * state: String
  * country: String
  * vatId: String
  * vatAmount: Int
  * secondTax: Int
  * createdAt: DateTime
  * invoiceNumber: String
  * status: Status
}

UserRole ||..|{ User
UserStatus ||..|{ User
UserRole ||..|{ User
User ||..|{ AccesLog
User ||..|{ RecoverPasswordLog
User ||..|{ Media
Media ||..|{ MediaMeta
MediaMeta }|..|| MediaType
LevelType ||..|{ Level
LevelType ||..|{ Level
AdType ||..|{ Ads
AdStatus ||..|{ Ads
User ||..|{ Ads
Conversation ||..|{ Message
User ||..|{ UserConversation
User ||..|{ Message
User ||..|{ Invoice
Invoice ||..|| Status

@enduml
