module.exports = [
    {
        id: 1,
        name: "house",
        house: 1,
        room: 0,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 0
    },
    {
        id: 2,
        name: "room",
        house: 0,
        room: 1,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 0
    },
    {
        id: 3,
        name: "garage",
        house: 0,
        room: 0,
        garage: 1,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 0
    },
    {
        id: 4,
        name: "storage",
        house: 0,
        room: 0,
        garage: 0,
        storage: 1,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 0
    },
    {
        id: 5,
        name: "office",
        house: 0,
        room: 0,
        garage: 0,
        storage: 0,
        office: 1,
        warehouse: 0,
        building: 0,
        new_building: 0
    },
    {
        id: 6,
        name: "warehouse",
        house: 0,
        room: 0,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 1,
        building: 0,
        new_building: 0
    },
    {
        id: 7,
        name: "building",
        house: 0,
        room: 0,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 1,
        new_building: 0
    },
    {
        id: 8,
        name: "new_building",
        house: 0,
        room: 0,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 1
    },
    {
        id: 1,
        name: "house",
        house: 1,
        room: 0,
        garage: 0,
        storage: 0,
        office: 0,
        warehouse: 0,
        building: 0,
        new_building: 0
    }
]