module.exports = [
  {
    userId: 1,
    billingAddress: 'Carrer Diagonal 000',
    postalCode: '08021',
    city: 'Barcelona',
    state: 'Catalonia',
    country: 'Spain',
    vatId: 'B00000000',
    vatAmount: 21,
    secondTax: 30,
    invoiceNumber: '1',
  },
  {
    userId: 2,
    billingAddress: 'Carrer Muntaner 000',
    postalCode: '08023',
    city: 'Barcelona',
    state: 'Catalonia',
    country: 'Spain',
    vatId: 'B00000001',
    vatAmount: 21,
    secondTax: 20,
    invoiceNumber: '2',
  },
  {
    userId: 1,
    billingAddress: 'Carrer Diagonal 000',
    postalCode: '08021',
    city: 'Barcelona',
    state: 'Catalonia',
    country: 'Spain',
    vatId: 'B00000000',
    vatAmount: 21,
    secondTax: 30,
    invoiceNumber: '3',
  },
  {
    userId: 3,
    billingAddress: 'Gran Via 000',
    postalCode: '28013',
    city: 'Madrid',
    state: 'Madrid',
    country: 'Spain',
    vatId: 'B00000002',
    vatAmount: 21,
    secondTax: 30,
    invoiceNumber: '4',
  },
]
