module.exports = [
	{name: "España", parent_id: null, level_type_id: 1},
	{name: "Cataluña", parent_id: 1, level_type_id: 2},
	{name: "Barcelona Provincia", parent_id: 2, level_type_id: 3},
	{name: "Barcelona Municipio", parent_id: 3, level_type_id: 4},
	{name: "Ciutat Vella", parent_id: 4, level_type_id: 5},
	{name: "El Raval", parent_id: 5, level_type_id: 6},
	{name: "El Barri Gòtic", parent_id: 5, level_type_id: 6},
	{
		name: "Sant Pere, Santa Catarina i la Ribera",
		parent_id: 5,
		level_type_id: 6,
	},
	{name: "La Barceloneta", parent_id: 5, level_type_id: 6},
	{name: "L'Eixample", parent_id: 4, level_type_id: 6},
	{
		name: "La Nova Esquerra de l'Eixample",
		parent_id: 6,
		level_type_id: 6,
	},
	{
		name: "L'Antiga Esquerra de l'Eixample",
		parent_id: 6,
		level_type_id: 6,
	},
	{name: "Dreta de l'Eixample", parent_id: 6, level_type_id: 6},
	{name: "Sagrada Família", parent_id: 6, level_type_id: 6},
	{name: "El Fort Pienc", parent_id: 6, level_type_id: 6},
	{name: "Sant Antoni", parent_id: 6, level_type_id: 6},
	{name: "Gràcia", parent_id: 4, level_type_id: 5},
	{name: "Vallcarca i els Penitents", parent_id: 7, level_type_id: 6},
	{name: "El Coll", parent_id: 7, level_type_id: 6},
	{name: "La Salut", parent_id: 7, level_type_id: 6},
	{name: "La Vila de Gràcia", parent_id: 7, level_type_id: 6},
	{
		name: "Camp d'en Grassot i Gràcia Nova",
		parent_id: 7,
		level_type_id: 6,
	},
	{name: "Horta - Guinardó", parent_id: 4, level_type_id: 5},
	{name: "Sant Genís dels Agudells", parent_id: 8, level_type_id: 6},
	{name: "Montbau", parent_id: 8, level_type_id: 6},
	{name: "La Vall d'Hebron", parent_id: 8, level_type_id: 6},
	{name: "Horta", parent_id: 8, level_type_id: 6},
	{name: "La Teixonera", parent_id: 8, level_type_id: 6},
	{name: "La Clota", parent_id: 8, level_type_id: 6},
	{name: "El Carmel", parent_id: 8, level_type_id: 6},
	{name: "La Font d'en Fargues", parent_id: 8, level_type_id: 6},
	{name: "Can Baró", parent_id: 8, level_type_id: 6},
	{name: "El Guinardó", parent_id: 8, level_type_id: 6},
	{name: "El Baix Guinardó", parent_id: 8, level_type_id: 6},
	{name: "Les Corts", parent_id: 4, level_type_id: 5},
	{name: "Pedralbes", parent_id: 9, level_type_id: 6},
	{
		name: "La Maternitat i Sant Ramon",
		parent_id: 9,
		level_type_id: 6,
	},
	{name: "Les Corts", parent_id: 9, level_type_id: 6},
	{name: "Nou Barris", parent_id: 4, level_type_id: 5},
	{name: "Ciutat Meridiana", parent_id: 10, level_type_id: 6},
	{name: "Vallbona", parent_id: 10, level_type_id: 6},
	{name: "Torre Baró", parent_id: 10, level_type_id: 6},
	{name: "Canyelles", parent_id: 10, level_type_id: 6},
	{name: "Les Roquetes", parent_id: 10, level_type_id: 6},
	{name: "La Guineueta", parent_id: 10, level_type_id: 6},
	{name: "Verdun", parent_id: 10, level_type_id: 6},
	{name: "La Trinitat Nova", parent_id: 10, level_type_id: 6},
	{name: "La Prosperitat", parent_id: 10, level_type_id: 6},
	{name: "El Turó de la Peira", parent_id: 10, level_type_id: 6},
	{name: "Porta", parent_id: 10, level_type_id: 6},
	{
		name: "Vilapicina i la Torre Llobeta",
		parent_id: 10,
		level_type_id: 6,
	},
	{name: "Camp de la Creu", parent_id: 10, level_type_id: 6},
	{name: "Can Peguera", parent_id: 10, level_type_id: 6},
	{name: "Sant Andreu", parent_id: 4, level_type_id: 5},
	{name: "Trinitat Vella", parent_id: 11, level_type_id: 6},
	{name: "Baró de Viver", parent_id: 11, level_type_id: 6},
	{name: "Sant Andreu de Palomar", parent_id: 11, level_type_id: 6},
	{name: "Bon Pastor", parent_id: 11, level_type_id: 6},
	{name: "El Congrés i Els Indians", parent_id: 11, level_type_id: 6},
	{name: "Navas", parent_id: 11, level_type_id: 6},
	{name: "La Sagrera", parent_id: 11, level_type_id: 6},
	{name: "Sants Montjuïc", parent_id: 4, level_type_id: 5},
	{name: "Sants - Badal", parent_id: 12, level_type_id: 6},
	{name: "Sants", parent_id: 12, level_type_id: 6},
	{name: "Hostafrancs", parent_id: 12, level_type_id: 6},
	{name: "La Font de la Guatlla", parent_id: 12, level_type_id: 6},
	{name: "La Marina de port", parent_id: 12, level_type_id: 6},
	{
		name: "La Marina del Prat Vermell",
		parent_id: 12,
		level_type_id: 6,
	},
	{name: "El Poble sec", parent_id: 12, level_type_id: 6},
	{name: "La Bordeta", parent_id: 12, level_type_id: 6},
	{name: "Sarrià - Sant Gervasi", parent_id: 4, level_type_id: 5},
	{
		name: "Vallvidrera, Tibidabo i Les Planes",
		parent_id: 13,
		level_type_id: 6,
	},
	{name: "Sarrià", parent_id: 13, level_type_id: 6},
	{
		name: "Sant Gervasi - La Bonanova",
		parent_id: 13,
		level_type_id: 6,
	},
	{name: "Les Tres Torres", parent_id: 13, level_type_id: 6},
	{name: "El Putxet i El Farró", parent_id: 13, level_type_id: 6},
	{name: "Sant Gervasi - Galvany", parent_id: 13, level_type_id: 6},
	{name: "Sant Martí", parent_id: 4, level_type_id: 5},
	{name: "El Besòs i el Maresme", parent_id: 14, level_type_id: 6},
	{name: "El Clot", parent_id: 14, level_type_id: 6},
	{
		name: "El Camp de l'Arpa del Clot",
		parent_id: 14,
		level_type_id: 6,
	},
	{
		name: "Diagonal Mar i el Front Marítim del Besòs i el Maresme",
		parent_id: 14,
		level_type_id: 6,
	},
	{
		name: "El Parc i la Llacuna del Poblenou",
		parent_id: 14,
		level_type_id: 6,
	},
	{name: "El Poblenou", parent_id: 14, level_type_id: 6},
	{name: "Provençals del Poblenou", parent_id: 14, level_type_id: 6},
	{name: "Sant Martí de Provençals", parent_id: 14, level_type_id: 6},
	{name: "La Verneda i la Pau", parent_id: 14, level_type_id: 6},
	{
		name: "La Vila Olímpica del Poblenou",
		parent_id: 14,
		level_type_id: 6,
	},
];
