module.exports = [
  { name: 'España', parentId: null, levelTypeId: 1 },
  { name: 'Cataluña', parentId: 1, levelTypeId: 2 },
  { name: 'Barcelona Provincia', parentId: 2, levelTypeId: 3 },
  { name: 'Barcelona Municipio', parentId: 3, levelTypeId: 4 },
  {
    name: 'Ciutat Vella',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'El Raval', parentId: 5, levelTypeId: 6 },
  { name: 'El Barri Gòtic', parentId: 5, levelTypeId: 6 },
  { name: 'Sant Pere, Santa Catarina i la Ribera', parentId: 5, levelTypeId: 6 },
  { name: 'La Barceloneta', parentId: 5, levelTypeId: 6 },
  {
    name: "L'Eixample",
    parentId: 4,
    levelTypeId: 5,
  },
  { name: "Dreta de l'Eixample", parentId: 6, levelTypeId: 6 },
  { name: 'La Sagrada Família', parentId: 6, levelTypeId: 6 },
  { name: 'El Fort Pienc', parentId: 6, levelTypeId: 6 },
  { name: 'Sant Antoni', parentId: 6, levelTypeId: 6 },
  { name: "L'Antiga Esquerra de l'Eixample", parentId: 6, levelTypeId: 6 },
  { name: "La Nova Esquerra de l'Eixample", parentId: 6, levelTypeId: 6 },
  {
    name: 'Gràcia',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Vallcarca i els Penitents', parentId: 7, levelTypeId: 6 },
  { name: 'El Coll', parentId: 7, levelTypeId: 6 },
  { name: 'La Salut', parentId: 7, levelTypeId: 6 },
  { name: 'La Vila de Gràcia', parentId: 7, levelTypeId: 6 },
  { name: "El Camp d'en Grassot i Gràcia Nova", parentId: 7, levelTypeId: 6 },
  {
    name: 'Horta - Guinardó',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Sant Genís dels Agudells', parentId: 8, levelTypeId: 6 },
  { name: 'Montbau', parentId: 8, levelTypeId: 6 },
  { name: "La Vall d'Hebron", parentId: 8, levelTypeId: 6 },
  { name: 'Horta', parentId: 8, levelTypeId: 6 },
  { name: 'La Teixonera', parentId: 8, levelTypeId: 6 },
  { name: 'La Clota', parentId: 8, levelTypeId: 6 },
  { name: 'El Carmel', parentId: 8, levelTypeId: 6 },
  { name: "La Font d'en Fargues", parentId: 8, levelTypeId: 6 },
  { name: 'Can Baró', parentId: 8, levelTypeId: 6 },
  { name: 'El Guinardó', parentId: 8, levelTypeId: 6 },
  { name: 'El Baix Guinardó', parentId: 8, levelTypeId: 6 },
  {
    name: 'Les Corts',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Les Corts', parentId: 9, levelTypeId: 6 },
  { name: 'Pedralbes', parentId: 9, levelTypeId: 6 },
  { name: 'La Maternitat i Sant Ramon', parentId: 9, levelTypeId: 6 },
  {
    name: 'Nou Barris',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Ciutat Meridiana', parentId: 10, levelTypeId: 6 },
  { name: 'Vallbona', parentId: 10, levelTypeId: 6 },
  { name: 'Torre Baró', parentId: 10, levelTypeId: 6 },
  { name: 'Canyelles', parentId: 10, levelTypeId: 6 },
  { name: 'Les Roquetes', parentId: 10, levelTypeId: 6 },
  { name: 'La Guineueta', parentId: 10, levelTypeId: 6 },
  { name: 'Verdun', parentId: 10, levelTypeId: 6 },
  { name: 'La Trinitat Nova', parentId: 10, levelTypeId: 6 },
  { name: 'La Prosperitat', parentId: 10, levelTypeId: 6 },
  { name: 'El Turó de la Peira', parentId: 10, levelTypeId: 6 },
  { name: 'Porta', parentId: 10, levelTypeId: 6 },
  { name: 'Vilapicina i la Torre Llobeta', parentId: 10, levelTypeId: 6 },
  { name: 'Can Peguera', parentId: 10, levelTypeId: 6 },
  {
    name: 'Sant Andreu',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Trinitat Vella', parentId: 11, levelTypeId: 6 },
  { name: 'Baró de Viver', parentId: 11, levelTypeId: 6 },
  { name: 'Sant Andreu de Palomar', parentId: 11, levelTypeId: 6 },
  { name: 'El Bon Pastor', parentId: 11, levelTypeId: 6 },
  { name: 'El Congrés i Els Indians', parentId: 11, levelTypeId: 6 },
  { name: 'Navas', parentId: 11, levelTypeId: 6 },
  { name: 'La Sagrera', parentId: 11, levelTypeId: 6 },
  {
    name: 'Sants Montjuïc',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'El Poble sec', parentId: 12, levelTypeId: 6 },
  { name: 'La Bordeta', parentId: 12, levelTypeId: 6 },
  { name: 'Sants - Badal', parentId: 12, levelTypeId: 6 },
  { name: 'Sants', parentId: 12, levelTypeId: 6 },
  { name: 'Hostafrancs', parentId: 12, levelTypeId: 6 },
  { name: 'La Font de la Guatlla', parentId: 12, levelTypeId: 6 },
  { name: 'La Marina de port', parentId: 12, levelTypeId: 6 },
  { name: 'La Marina del Prat Vermell', parentId: 12, levelTypeId: 6 },
  {
    name: 'Sarrià - Sant Gervasi',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Vallvidrera, Tibidabo i Les Planes', parentId: 13, levelTypeId: 6 },
  { name: 'Sarrià', parentId: 13, levelTypeId: 6 },
  { name: 'Sant Gervasi - La Bonanova', parentId: 13, levelTypeId: 6 },
  { name: 'Les Tres Torres', parentId: 13, levelTypeId: 6 },
  { name: 'El Putxet i El Farró', parentId: 13, levelTypeId: 6 },
  { name: 'Sant Gervasi - Galvany', parentId: 13, levelTypeId: 6 },
  {
    name: 'Sant Martí',
    parentId: 4,
    levelTypeId: 5,
  },
  { name: 'Camp de la Creu', parentId: 14, levelTypeId: 6 },
  { name: 'El Besòs i el Maresme', parentId: 14, levelTypeId: 6 },
  { name: 'El Clot', parentId: 14, levelTypeId: 6 },
  { name: "El Camp de l'Arpa del Clot", parentId: 14, levelTypeId: 6 },
  { name: 'El Parc i la Llacuna del Poblenou', parentId: 14, levelTypeId: 6 },
  { name: 'La Vila Olímpica del Poblenou', parentId: 14, levelTypeId: 6 },
  { name: 'El Poblenou', parentId: 14, levelTypeId: 6 },
  { name: 'Diagonal Mar i el Front Marítim del Besòs i el Maresme', parentId: 14, levelTypeId: 6 },
  { name: 'Provençals del Poblenou', parentId: 14, levelTypeId: 6 },
  { name: 'Sant Martí de Provençals', parentId: 14, levelTypeId: 6 },
  { name: 'La Verneda i la Pau', parentId: 14, levelTypeId: 6 },
]
