name: BE Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and deploy
        run: |
          cd scripts
          bash dev.deploy.be.sh
