# name: DEVELOPMENT FRONTEND ITA DIRECTORY
# on:
#   push:
#     branches:
#       - develop
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js 14.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 14.x

#     - name: Install Packages
#       run: npm install

#     - name: Build page
#       run: npm run build
#       env:
#         CI: true
