name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: build and deploy
      — run: | 
          pwd
          cd scripts
          bash dev.deploy.sh