name: frontend

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: install dependencies
        run: cd ./frontend && npm ci

      - name: lint
        run: cd ./frontend && npm run lint

      - name: test
        run: cd ./frontend && npm run test

      - name: build
        run: cd ./frontend && npm run build
